### ISSUE TITLE
newbot serve GUI

### ISSUE THREAD

**Issue by IzydorDPS** [newbotjs/newbot-framework#17]
Hi,
there is any way to change language of the interface in GUI emulator because, some elements are in French which dont look good during presentation.

**Comment by RSamaium** [comment]
Hello,

The language is automatically selected according to the browser language (either English or French). French is the default language (normally it should be English ...)

I come back to you with a possibility to change the language.

In the meantime, if you want to give a presentation, change the browser language (set it to English).
