### ISSUE TITLE
Documentation ExpressJS and Socket.io empty paragraphs

### ISSUE THREAD

**Issue by IzydorDPS** [newbotjs/newbot-framework#18]
Hi,
I was looking for serverside code example but the documentation looks unfinished or like somthing has broken.

https://newbot.io/en/docs/engine/server.html#doc

Where i can find some examples to this topic?

**Comment by RSamaium** [comment]
Hello,

Indeed, the Embed CodeSandbox does not work. Thanks for reporting.

Here is a working CodeSandbox:

https://codesandbox.io/s/execute-newbot-expressjs-and-socketio-q05si

**Comment by RSamaium** [comment]
Updated documentation
