### ISSUE TITLE
newbot-server and socket.io @Format('quickReplies', choices) crash

### ISSUE THREAD

**Issue by IzydorDPS** [newbotjs/newbot-framework#19]
Hi,
i have a quiz skill that is similar to the quiz from example and it works perfectly on newbot serve but when i make "newbot build -n 1" and run it by "node server" (server from example as well)  it crash immediately when  execute @Format('quickReplies', choices) 
throwing error:

"(node:11724) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `session` of 'undefined' or 'null'.
    at Converse.format (C:\Users\Damian\WebstormProjects\GrowUP_chatbot\dist\node\bot.js:1:5667)
    at C:\Users\Damian\WebstormProjects\GrowUP_chatbot\node_modules\newbot\src\interpreter.js:859:66
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was no
t handled with .catch(). (rejection id: 1)
(node:11724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

Everything works when i remove Format('quickReplies', choices)

**Comment by RSamaium** [comment]
Hello,

If you are using the `newbot-formats` module. Pass a session object when you run the chatbot

```js
converse.exec('Hey', 'user id', {
    output(text, done) => {
        console.log(text)
        done()
    },
    data: {
        session: {
            message: {
                source: 'website'
            }
        }
    }
})
```

Documentation : https://newbot.io/en/docs/avanced/data.html#doc

**Comment by IzydorDPS** [comment]
Great! that works :)

Would be great if updated version appear on NewBot ExpressJS and SocketIo  Sandbox example.
Because there are some small differences like 

```
{
    output(text, done) => {
        console.log(text)
        done()
    }

```
vs

```
 (output, done) => {
      socket.emit("botReply", output);
      done();
}

```
it dont work in second case


This works:

```
io.on("connection", socket => {
    socket.on("userText", str => {
        converse.exec(str, socket.id, {
            output(output, done) {
                socket.emit("botReply", output);
                done();
            },
            data: {
                session: {
                    message: {
                        source: 'website'
                    }
                }
            }
        });
    });
});
```
