### ISSUE TITLE
Complete Structure option with newbot new <botname> fails

### ISSUE THREAD

**Issue by veerjainATgmail** [newbotjs/newbot-framework#2]
[BUG]
[Ubuntu 18.x]
[latest master]

Notes:
installed using yarn instead of npm
newbot new bot, only the basic file option works fine.

**Error**
newbot new my-chatbot1
? What do you want to integrate into your project? **Complete Structure (native NLP, production serv
er, pre-integrated modules, i18n)**
  ❯ Create project
    ✔ Create Folder
    ✖ Copy and paste templates
      → ENOENT: no such file or directory, open '/usr/local/share/.config/yarn/global/node_modules
…
    Install package dependencies with npm
    Create NLP Model
newbot new <name>

create a new project

Commands:
  newbot serve                   start the server
  newbot build                   build your chatbot skills
  newbot emulator                Run the console emulator
  newbot generate <type> <name>  Run the console emulator
  newbot train                   train your chatbot with NLP system
  newbot setwebhooks             Assign webhooks from different platforms to
                                 your production server
  newbot deploy                  Deploy your chatbot to NewBot Cloud
  newbot logout                  Logout to NewBot Cloud

Options:
  -h, --help
  -p, --port                     Listen on port (3000 by default)
  -n, --ngrok, --node            Build NodeJS only
  -c, --cloud                    Test your chatbot in NewBot Cloud
  -e, --entry, --entry, --entry  name of entry file (main.js by default)
  --cf, --config                 name of config file (newbot.config.js by
                                 default)
  -s, --source                   Simulate platform [messenger, line, slack,
                                 telegram, viber]
  -l, --lang                     Set user language (ex: fr_FR, en_EN, es_ES,
                                 ...)
  --sk, --skill                  Test a skill in skills directory
  -?, --help                     Show help                             [boolean]
  -v, --version                  Show version number                   [boolean]

Examples:
  newbot serve -p 5000  Change port to 5000

{ Error: ENOENT: no such file or directory, open '/usr/local/share/.config/yarn/global/node_modules/newbot-cli/dist/commands/../../templates/init/server/app.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at copy (/usr/local/share/.config/yarn/global/node_modules/newbot-cli/dist/commands/new.js:208:72)
    at /usr/local/share/.config/yarn/global/node_modules/newbot-cli/dist/commands/new.js:236:49
    at new Promise (<anonymous>)
    at new F (/usr/local/share/.config/yarn/global/node_modules/core-js/library/modules/_export.js:36:28)
    at Task.task (/usr/local/share/.config/yarn/global/node_modules/newbot-cli/dist/commands/new.js:173:48)
    at Promise.resolve.then.then.skipped (/usr/local/share/.config/yarn/global/node_modules/listr/lib/task.js:167:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path:
   '/usr/local/share/.config/yarn/global/node_modules/newbot-cli/dist/commands/../../templates/init/server/app.js',
  context:
   [Object: null prototype] { packages: [ 'newbot', 'newbot-formats' ] } }

**Comment by RSamaium** [comment]
Hello,

The problem has been fixed. Update the latest version : 

`npm install -g newbot-cli@latest`

or

`yarn global add newbot-cli@latest`

**Comment by veerjainATgmail** [comment]
Thanks !!.
