### ISSUE TITLE
newbot build -n 1 and unable to set .env variables

### ISSUE THREAD

**Issue by IzydorDPS** [newbotjs/newbot-framework#20]
Hi,
Is there a way to set process.env.NODE_ENV variable to use in build?
Everything works fine when im using "newbot serve"

In documentation i only saw a tip for cloud version of newbot

**Comment by RSamaium** [comment]
Hello and sorry for my late reply.

The build command does not use the NODE_ENV environment variable.

this variable can be read when you start your NodeJS server

Example (`index.js` file)

```js
const { NewBot } = require('newbot')
const converse = new NewBot({
    code: `
        @Event('start')
        start() {
            > Env is { NODE_ENV }
        }
    `,
    constants: {
        NODE_ENV: process.env.NODE_ENV
    }
})

converse.exec('Hey', 'user id', (output, done) => {
    console.log(output)
    done()
})
```

and

`NODE_ENV=production node index`

> I put the skill directly in the JS but it is identical to putting the export of the built file
> `new NewBot(yourBuiltFile)`
