### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by JFDonovan** [newbotjs/newbot-framework#21]
When I ran the command "newbot new testNewbot" it threw the following error:

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'jsonwebtoken'

It seems like if I try to do anything with the newbot cli (any newbot cmd) it gives this error.

**Comment by RSamaium** [comment]
Hello,

Sorry for my late answer. I think you had a problem when installing NewBot ClI on your machine.
Indeed, [unit tests](https://travis-ci.org/github/newbotjs/newbot-cli/builds/652477245) show the modules are not missing. Have you tried reinstalling NewBot CLI? Or maybe install it locally?

(local) In a directory: 
```sh
npm init -y
npm install newbot-cli
npx newbot new testNewbot
```

**Comment by IzydorDPS** [comment]
I had this problem too and adding jsonwebtoken to package.json or global install helped.
I also recommend using LTS version of nodejs, because newest version give me some problems with dependencies.
