### ISSUE TITLE
quickReplies error on FB Messenger

### ISSUE THREAD

**Issue by NenaBas** [newbotjs/newbot-framework#22]
The quickreplies format doesn't seem to work on the FB Messenger platform. Everytime it is used, and error is thrown and the bot stops responding:
Here is the error. I went into the Messenger.js file to do a small print to detect the problem.
![messenger_error_quickreplies](https://user-images.githubusercontent.com/9417396/88036002-9e79f580-cb4b-11ea-9e98-285302c5e049.png)

**Comment by RSamaium** [comment]
Hello,

Sorry for my late answer. I'll look it over and get back to you.

**Comment by RSamaium** [comment]
From now on, NewBot Framework focuses on creating a conversational scenario (it is difficult to maintain compatibility for each instant messaging platform)

Normally, you can link it with any instant messenger but you will have to code it yourself.
