### ISSUE TITLE
Forum for questions?

### ISSUE THREAD

**Issue by NenaBas** [newbotjs/newbot-framework#23]
Hello, 
I have started using the framework for a work project since it seems that it can be very useful. However, I have been struggling to understand some things and I have a lot of questions regarding on the usage of some things and I think that others had and will have the same problem. 
Furthermore, I have tried posting on stackoverflow but the` newbot_framework` hashtag doesn't already exist there and I don't have enough reputation to create it. 
So, can you please add a forum for people to ask questions and post examples regarding the framework'?

**Comment by RSamaium** [comment]
Hello,

Thank you for already using NewBot Framework. We are looking forward to your feedback and questions. 
We will what kind of forum we can add
