### ISSUE TITLE
Add the chatbot into a simple webpage

### ISSUE THREAD

**Issue by NenaBas** [newbotjs/newbot-framework#25]
I need help to understand how to be able to use the chatbot into a webpage I have designed, without the need to deploy the bot into Newbot Cloud. 
Can you please show me an example because I cannot seem to find enough info on the documentation?
Furthermore, how can I test it in my webpage with `newbot serve` and the resulting link provided by **ngrok**?

**Comment by RSamaium** [comment]
Hello,

* Deploy in Browser : https://newbot.io/en/docs/essential/browser.html#doc
or 
* Deploy with NodeJS: https://newbot.io/en/docs/engine/express.html#doc
