### ISSUE TITLE
newbot serve  not working

### ISSUE THREAD

**Issue by suyashcjoshi** [newbotjs/newbot-framework#26]
Was really hoping to use this library but can't use it as it's giving error:

```
$ newbot serve
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'jsonwebtoken'
...
...
```

**Comment by RSamaium** [comment]
Hello,

Sorry for my late response. Update NewBot CLi (latest version)

npm install -g newbot-cli@latest

**Comment by RSamaium** [comment]
Here are the new guidelines to install NewBot:

https://docs.newbot.io/get-started/install
