### ISSUE TITLE
issue creating a project

### ISSUE THREAD

**Issue by OliverHarris-JBC** [newbotjs/newbot-framework#27]
When I install newbot using NPM says lots of the modules are deprecated

When i go to create bot it shows the following and no folder is created.

![image](https://user-images.githubusercontent.com/58073915/101175303-e7cf6b00-363c-11eb-9cfb-070de4e918da.png)

Can you advise please help

**Comment by RSamaium** [comment]
Hello,

Sorry for my late response. Update NewBot CLi (latest version)

`npm install -g newbot-cli@latest`

**Comment by RSamaium** [comment]
Here are the new guidelines to install NewBot:

https://docs.newbot.io/get-started/install
