### ISSUE TITLE
Numerous warnings on install - ERROR on newbot new

### ISSUE THREAD

**Issue by Jonbene** [newbotjs/newbot-framework#28]
Hello there,
when installing i receive multiple Warnings on the console.

Is there anything i can do upon installation or is this package related?

Thanks for help!

Greets 
Jonas
![newbot-warnings](https://user-images.githubusercontent.com/51970171/117951256-48618300-b314-11eb-8ba1-38ca59bbc7e2.JPG)

**Comment by Jonbene** [comment]
Also - on newbot new... i receive the following error with no installation.

![newbot-error-install](https://user-images.githubusercontent.com/51970171/117951610-9e362b00-b314-11eb-865a-a2259db7fcb4.JPG)

**Comment by RSamaium** [comment]
Here are the new guidelines to install NewBot:

https://docs.newbot.io/get-started/install
