### ISSUE TITLE
nlp.js Integration with newbot

### ISSUE THREAD

**Issue by AravindR7** [newbotjs/newbot-framework#5]
Integrating nlp js for intent and entity recognition

**Comment by RSamaium** [comment]
Hello,

Do you have a result on localhost:3000 ?

**Comment by AravindR7** [comment]
no the result is not appearing on localhost:3000

**Comment by RSamaium** [comment]
Hmm, can you share your code?

**Comment by AravindR7** [comment]
hey

**Comment by AravindR7** [comment]
@Intent('greeting', [
    'Hey',
    'Hello',
    'Good afternoon',
    'Good morning',
    'Hi'
])
hello() {
    > Hey !
}

@Intent('agent.age')
agentAge() {
    > { :intent}
}

@Event('start')
nameFunction() {
    >  I am Chatbot
}

@Event('startAndIntent')
nameFunction() {
   > I am Chatbot. I will try to answer your question
}

/*
@Event('nothing')
nameFunction() {
    > What ?
}
*/
//@Event('on', 'my-event')
//nameFunction() {
//    > Ton nom est { :event.name }
//}

@Event('start') 
start() {
    > What your name ?
    Prompt()
    > Hello !
}

@Event('start')
start() {
    ---
    > Hello
    > Good Afternoon
    ---
}

**Comment by AravindR7** [comment]
(hello.converse)
@Intent('agent.age')
agentAge() {
    > { :intent}
}
this one is just to handle one intent(age)

there are many more intents the model.nlp contain 
how to handle all those and get result in localhost:3000


(hello.js)
import formats from 'newbot-formats';
import code from './hello.converse';
import rp from 'request-promise';


export default {
    code,
    nlp: {
        async myApi(text, userId, converse) {
            const user = converse.users.get(userId)
            const languageCode = user.getLang()
            const ret = await rp({
                url: 'http://localhost:5000/api',
                method: 'POST',
                body: {
                    text,
                    languageCode
                },
                json: true
            })
            const reg = /[a-z]+\.[a-z]+/
            console.log(reg.test(ret.intentName))
            console.log(ret.answer);
            return {
                [ret.intentName]() {
                    return ret.answer
                }
            }
        }
    },
    skills: {
        formats
    }
}

or does the above code need any changes
