### ISSUE TITLE
Problem faced in the quiz bot. 

### ISSUE THREAD

**Issue by dhannya34** [newbotjs/newbot-framework#6]
I faced an issue running the Quiz bot, it's not showing 2nd question after I have selected 1st answer option. It's not propagating the loop. Could you please help me fix this issue.

I think there's a problem with this line:-
index = Array.indexOf(question.choices, :text)
![Screenshot from 2019-10-05 15-39-00](https://user-images.githubusercontent.com/44765574/66253524-4114e380-e787-11e9-898f-7870d7b91c16.png)

**Comment by RSamaium** [comment]
Thanks for indicating the bug

You can update the version in your project :

`npm install newbot@latest`

**Comment by dhannya34** [comment]
But it couldn't classify the correct and incorrect answers. 
![Screenshot from 2019-10-09 16-17-13](https://user-images.githubusercontent.com/44765574/66475128-57d17800-eab0-11e9-8606-8a48bf72add4.png)
Here it incorrectly classified the correct answer as 'It's wrong'.
Could you please fix this issue.

**Comment by RSamaium** [comment]
I do not have any worries on my side. Can you send me the logs (Debug tab> Download Log)

**Comment by dhannya34** [comment]
I have attached the Log.
[newbot_log_4_2019-10-10T11_20_25.084Z.zip](https://github.com/newbotjs/newbot-framework/files/3712351/newbot_log_4_2019-10-10T11_20_25.084Z.zip)

**Comment by RSamaium** [comment]
Ok, you have two solutions (to choose) : 

Use `index = Array.indexOf(question.choices, :text)` in your conversational code

_or_

create your own function 

In your JS file : 
```js
import formats from 'newbot-formats'
import code from './quiz.converse'

export default {
    code,
    skills: {
        formats
    },
    functions: {
        indexOf(array, text) {
            return array.indexOf(text)
        }
    }
}
```

and use your function : 

Use `index = indexOf(question.choices, :text)` in your conversational code
